openapi: 3.0.1
info:
  title: catalog upload service
  description: api for uploading catalog data
  version: 1.0.0
servers:
  - url: http://localhost:1337
paths:
  /upload:
    post:
      operationId: UploadController_uploadFile
      parameters: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CreateUploadRequest'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '../Schema/Http/ImageMetadataResponse.json'
      tags:
        - upload
    put:
      operationId: UploadController_updateFile
      parameters: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UpdateUploadRequest'
      responses:
        '200':
          description: ''
      tags:
        - upload
  '/upload/{id}':
    get:
      operationId: UploadController_findFile
      parameters:
        - $ref: '#/components/parameters/idParam'
      responses:
        '200':
          description: ''
      tags:
        - upload
    delete:
      operationId: UploadController_deleteFile
      parameters:
        - $ref: '#/components/parameters/idParam'
      responses:
        '200':
          description: ''
      tags:
        - upload
components:
  parameters:
    idParam:
      name: id
      in: path
      description: id of requested item
      required: true
      schema:
        type: string
        format: uuid
  schemas:
    CreateUploadRequest:
      type: object
      properties:
        additionalData:
          allOf:
            - $ref: '../Schema/ImageMetadata/ImageMetadata-Create.json'
        file:
          type: array
          description: the main data files to upload
          items:
            type: string
            format: binary
        additionalFiles:
          type: array
          description: additional files to upload with the main data file
          items:
            type: string
            format: binary
      required:
        - additionalData
    UpdateUploadRequest:
      type: object
      properties:
        additionalData:
          allOf:
            - $ref: '../Schema/ImageMetadata/ImageMetadata-Update.json'
        files:
          type: array
          description: the main data files to upload
          items:
            type: string
            format: binary
        additionalFiles:
          type: array
          description: additional files to upload with the main data file
          items:
            type: string
            format: binary
      required:
        - additionalData
